### ISSUE TITLE
API key is not to be uploaded publicly

### ISSUE THREAD

**Issue by anjannair** [ComputerScientist-01/Weather-app-heroku#3]
https://github.com/ComputerScientist-01/Weather-app-heroku/blob/e1ca4ffe871b63e8262d5559fff51532879cc670/weather_app.py#L11

Although this API key is now invalid (the hosted app on Heroku fails to work), you are not supposed to directly upload your API keys on GitHub. Use [python-dotenv](https://pypi.org/project/python-dotenv/) to deal with it. 
Go to Heroku settings and follow the steps like [this](https://github.com/anjannair/Rufus-Discord-Bot/wiki/The-Heroku-Hosting#head-over-to-settings-and-config-vars-and-reveal-config-vars-this-is-where-all-your-tokens-will-go-replace-the-value-with-the-token) to put the API key in the Heroku enviornment

Other links to help:- [Stackoverflow - What is the use of python-dotenv? ](https://stackoverflow.com/questions/41546883/what-is-the-use-of-python-dotenv)

**Comment by ComputerScientist-01** [comment]
Thanks a lot for this . let me make this change ASAP

**Comment by ComputerScientist-01** [comment]
No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
I'm having this error

**Comment by ComputerScientist-01** [comment]
the issue has been resolved

**Comment by anjannair** [comment]
Well done!
